version: "2"
services:
  node:
    image: "node:9"
    user: "node"
    working_dir: /
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/eshop/databases
    ports:
      - "80:8000"
    expose:
      - "80"
    command: "npm start"